### ISSUE TITLE
Unable to fetch maint updates (403)

### ISSUE THREAD

**Issue by Xwilarg** [Tibowl/Asashio#6]
Hey,

I'm trying to run the bot locally but I keep having the following errors:
```
[2021-12-13T14:23:23.858] [ERROR] MaintManager - Unable to fetch maint updates (403)
[2021-12-13T14:23:24.452] [ERROR] MaintManager - Unable to fetch maint updates (403)
```

I did everything that was in the README and added everything in my config.json so I'm not sure what is missing

**Comment by Tibowl** [comment]
This is due to C2's region block (where the [gadget server](http://203.104.209.7/) requires a jp ip), you'll need to host the bot on a Japanese IP or set up a Japanese VPN if you want maintenance updates/version number announcements to work (in .follow).

**Comment by Xwilarg** [comment]
![image](https://user-images.githubusercontent.com/20053454/145823042-3a4b63c4-31dd-410b-b248-26a8627cc409.png)
Even after connecting to a VPN it still doesn't work

Is there a way to skip this step?

**Comment by Tibowl** [comment]
This only affects the maintenance/version follows, you can comment the checks out in [MaintManager](https://github.com/Tibowl/Asashio/blob/master/src/utils/MaintManager.ts#L13-L14) if the prints/extra network usage are annoying/unwanted.

**Comment by Xwilarg** [comment]
Thanks for the help
